---
roles:
  - name: aisbergg.systemd_resolved
  - name: githubixx.ansible_role_wireguard
  - name: hugoprudente.envoyproxy
    version: v0.1.3
  - name: patrickjahns.promtail
  - name: nginxinc.nginx_config
  - name: stefangweichinger.ansible_rclone
  - name: diademiemi.syncthing

collections:
  - name: community.general
  - name: community.kubernetes
  - name: nginxinc.nginx_core
  - name: artis3n.tailscale
