---
roles:
  - name: aisbergg.systemd_resolved
  - name: artis3n.tailscale
  - name: githubixx.ansible_role_wireguard
  - name: hugoprudente.envoyproxy
    version: v0.1.3
  - name: patrickjahns.promtail
  - name: ajaykumar4.zerotier
    src: https://github.com/ajaykumar4/ansible-role-zerotier.git
    version: 2386e44142c723c6d67b5206164aec071255c240
  - name: nginxinc.nginx_config
  - name: ansible-community.ansible-vault
    src: https://github.com/ansible-community/ansible-vault.git
    version: v3.3.2
  - name: stefangweichinger.ansible_rclone
  - name: diademiemi.syncthing

collections:
  - name: community.general
  - name: community.kubernetes
  - name: nginxinc.nginx_core
